name: Auto Assign on Help Wanted

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
    
permissions:
  issues: write
  pull-requests: write
  
jobs:
  assign-helper:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'help wanted'
    steps:
      - name: Assign user to issue or PR
        uses: actions/github-script@v7
        with:
          script: |
            const issueOrPr = context.payload.issue || context.payload.pull_request;
            const assignees = ['copilot-swe-agent[bot]'];

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueOrPr.number,
              assignees
            });
