name: Auto-Assign Copilot Agent

on:
  issues:
    types: [opened]

jobs:
  assign-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign Copilot Agent
        uses: actions-ecosystem/action-assign@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: Copilot
